version: '3'
services:
  model-server:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 384M
        reservations:
          memory: 128M
    restart: unless-stopped
  
  prometheus:
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    restart: unless-stopped
  
  grafana:
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    restart: unless-stopped